### ISSUE TITLE
Consider encoding: base-emoji

### ISSUE THREAD

**Issue by victorb** [multiformats/multibase#45]
Since the [proposals were removed from the readme](https://github.com/multiformats/multibase/commit/67b1cee1de5a5a78e9ca5d24471dbf4e6211ad11#diff-04c6e90faac2675aa89e2176d2eec7d8), I'm adding this issue so we don't lose track of it.

base-emoji would be helpful to get humans to more easily verify that things are correct on both sides of some communication. For example, see https://github.com/ipfs-shipyard/peer-pad/issues/134#issuecomment-443733449 of one use-case

**Comment by MidnightLightning** [comment]
I just found this proposal, and I'd be very interested to see an emoji-base be developed further. But why limit to 256 emojis? There's currently enough emojis to jump up to a list of 1,024 emojis without using flags or "zero-width-joiner"-style emojis. Using a higher lexicon of possibilities would allow compressing the data even further.

I explored this idea a few years back in [this blog article](https://medium.com/@midnightlightning/the-future-of-identifiable-identifiers-79ddc92a16aa), and defined a 1,024-emoji encoder over at https://github.com/MidnightLightning/radix-emoji as a sample.

**Comment by rvagg** [comment]
Thanks @MidnightLightning, interesting post. The example: `1MgPvHbMKCXZqeBpDTPH9a8B9cNr8E7hv6` as `🆓🕒🚣🍮⛰🍂🗣☪🐌🏒⚫💃🚧🙉👸📤🍤🏓🙋⏱🎂` is illuminating. Technically fewer characters, but takes up more horizontal space on any rendering and is 80 bytes vs 34; so not exactly an ideal practical format for real-world use.
I'm going to close this issue, we probably should have done so last year, because we had `base256emoji` added (and implemented in the Go and JS libraries), which gives us an emoji encoding, which, admittedly, is even more wasteful. But again, I'm not sure this is really a practical real-world encoding that has any benefit beyond the novelty of it, regardless of how much you attempt to compress it.

**Comment by MidnightLightning** [comment]
> I'm not sure this is really a practical real-world encoding that has any benefit beyond the novelty of it, regardless of how much you attempt to compress it.

@rvagg The benefits of this encoding style are not in how the data is stored, but in how humans can interpret it. As noted in the original comment in this issue (how peer-pad uses emoji-encoding), humans being able to say/identify the emojis more easily (as opposed to learning the Phonetic Alphabet to be able to relay `bdEBCEEeB` verbally accurately to another human). Also, as my article points out, humans being able to distinguish differences in emojis is more likely. Even with different systems using different pictures for different emojis, it's likely anyone would still be able to say "[that's](https://emojipedia.org/airplane/) an airplane". Also, then noting differences in a string of characters would be easier if they're emojis (assuming good choices were made in which emojis to be part of the lexicon; the same way that Base-58 removed "0OIl characters").

So, I agree the proper use of base256emoji-encoding is not using it as the primary way that a binary data is stored. But there are several benefits to using it as a display method. I'd much rather see base256emoji well-documented and describe for developers the areas where emoji-encoding is beneficial, than just sweeping it under the rug. If base256emoji is implemented, then should the README and documentation be updated to move it out of "draft" status?

**Comment by rvagg** [comment]
Well, `draft` reflects a certain amount of uncertainty about the format—even after implementing there was some shuffling in which emojis were used because a couple of the original choice didn't have a nice render form on some platforms.

> draft - these encodings have been proposed but are not widely implemented and may be removed.

implemented in two places, unsure if anyone is actually using them for anything practical. The bar is somewhat subjective but I don't feel that it's moved beyond `draft` for now.
