### ISSUE TITLE
Remove canonization of Base2

### ISSUE THREAD

**Issue by fabianhjr** [multiformats/multibase#49]
Base2 should be taken as-is. If it isn't 8k+1 in length it should be considered invalid since the missing zeros could be either from the start or the end.

**Comment by Stebalien** [comment]
It's defined to be from the start. Really, I'd also be fine *always* trimming leading zeros. This is to allow people to write things like 01000 to mean 8 (instead of requiring a full 000001000).

We could change it given that it isn't used in practice but I'd like a stronger motivation (given that 01000 is really convenient).
