### ISSUE TITLE
proposal: base4cloaky

### ISSUE THREAD

**Issue by Jorropo** [multiformats/multibase#97]
This is a base4 (2bits per codepoint) made of:
- `U+2060` WORD JOINER `⁠` 0
- `U+2061` FUNCTION APPLICATION `⁡` 1
- `U+2062` INVISIBLE TIMES `⁢` 2
- `U+2063` INVISIBLE SEPARATOR `⁣` 3

With a special particularity, invalid codepoints are just skipped over.
`U+2024` INVISIBLE PLUS `⁤` is then used to indicate the end of the data.
In case the data is incomplete when the terminator is reached, the remaining byte is zero padded.

The key would be `U+2060`.

This allows to hide thoses CIDs in other pieces of text (that includes other CIDs).
Here is a random example:
```
⁠Th⁠is is a⁡ to⁢t⁡al⁢⁠l⁢⁡y ⁡nor⁠⁢m⁡al p⁢⁠⁡ie⁡ce ⁢o⁡f t⁠⁡e⁡xt⁤.
```

**Comment by rvagg** [comment]
What's the multibase code for this though? Your example doesn't have one.

Without that, and invalid codepoints skipped, is this really a multibase? Maybe this deserves to be specced somewhere else as a generic base encoding instead? Multibase is for text encoding with a known, unique, signifier prefix. Base encodings have generic application and you can base encode any CID without using multibase; such as with this encoding scheme.

**Comment by Jorropo** [comment]
FYI, this is an other joke multibase than wouldn't be recomanded like #88. I would understand if you say that two would be too much.

> What's the multibase code for this though? Your example doesn't have one.

> The key would be `U+2060`.

I'm listing it as unicode literal representation since it's an invisible zero width character.


It's a non unique encoding, because the parser skip anything not in the `U+2060 - U+2065` range multiple representation of the same data exists.
However, we already have other non unique encodings, Bases 11 through 36 are case insensitive making them technically non unique.

The reason I think skipping over unknown character is valuable is that, on their own thoses characters are zero width. Making them hard to copy paste. If you embed them in some texts tho, you can then just copy paste the word and know you also got the meaning full inside.
Thoses characters are non word breaking some you can use the double click + hold or control + direction + shift to do a word selection and they don't break the word (so it selects the complete word).

That also allows us to create infinitely many ~~confusing~~ *funny* situations. Imagine sending something that looks like a dag-cbor sha256 CID. But is actually a dag-json, blake2b-512 because you stuffed invisible characters in it. (*to be used responsively at users discretion*)

I don't think that present any major issues for the implementations, they can have a custom dictionary of carrier sentences and pick one at random every time they encode it.
Architecturally it's a bit hard for the test suite, since this would make the output non deterministic, but a simple `test` flag that cycles between the available sentences instead of picking them at random sounds doable.

**Comment by rvagg** [comment]
🤦 ok, I see .. so you could U+2060 in front of `bafy...` and multibase would use this encoding instead...

so .. I think that presents a bit of a security challenge if we're enabling a way of intentionally obfuscating CIDs, or anything else that's base encoded.. Even though base encoded strings don't tend to be very human readable or memorable, but there are cases where this isn't so true. Say I have a blockchain address multibase encoded. I'm familiar enough with at least one of my crypto wallet addresses that I can spot it very easily in a list of them. So if you have a situation where someone has a human-memorable multibase encoded string; an attack vector could be to present someone with a string that they copy and paste and you rely on them to recognise it as _friendly_ because it hits the memorable part of their brain, but when they paste it in, it leads to something entirely different. You end up with situations slightly similar to a bank scam where the address money is going to isn't what you think it is. We could probably think up other forms of this.

So ... maybe this is interesting as an alt implementation, but probably not a good idea to bundle with "standard" implementations such that it can subvert safe paths. But I'm not sure what that means for this repo—maybe that it can't go in the table, but could be documented as a fun alt?

**Comment by Jorropo** [comment]
The security aspect is definitely real but it's also what makes it fun.

I knew this was edgy, but didn't thought about crypto wallets (where this is a serious issue).

I think due to that potential severity a sensible multibase implementations would omit or at least make this one optin.

However I don't know which application would enable decoding thoses. (rendering it kinda useless)
