### ISSUE TITLE
Alphabets code value are no longer all ASCII 

### ISSUE THREAD

**Issue by sg495** [multiformats/multibase#99]
In the [FAQ section of README.md](../blob/master/README.md#FAQ) it is stated that:

> The code values are selected such that they are included in the alphabets of the base they represent. For example, f is the base code for base16 (hex), because f is in hex's 16 character alphabet. Note that the alphabets can be encoded in ASCII or UTF8. We have not found a case needing something else.

With the introduction of `base256emoji`, this is no longer the case, so it might be worth re-wording the section to avoid confusion.

**Comment by Stebalien** [comment]
> or UTF8

?

**Comment by Stebalien** [comment]
And... I need to learn how to read.

**Comment by Stebalien** [comment]
Yeah, we should probably change this to "encoded in UTF8, and most can be encoded in ASCII".

**Comment by rvagg** [comment]
https://github.com/multiformats/multibase/pull/100

**Comment by Jorropo** [comment]
IMO it's not an issue because thx to unicode people being smart, any non ascii UTF8 codepoint is invalid ASCII.

To any non utf8 aware ascii implementation any utf8 base just look like a base that doesn't exists.

If you are using utf16 or utf32 that doesn't apply but if you do that you aren't using ascii then.
